### ISSUE TITLE
Markdown translation

### ISSUE THREAD

**Issue by KINGSABRI** [Malajab/API-Security#2]
Here are all the Markdown translation tasks

### Tasks list
- [x] Transalte 0x00-header.md 
- [x] Transalte 0x00-notice.md 
- [x] Transalte 0x00-toc.md 
- [x] Transalte 0x01-about-owasp.md 
- [x] Transalte 0x02-foreword.md 
- [x] Transalte 0x03-introduction.md 
- [x] Transalte 0x04-release-notes.md 
- [x] Transalte 0x10-api-security-risks.md 
- [x] Transalte 0x11-t10.md 
- [x] Transalte 0xa1-broken-object-level-authorization.md 
- [x] Transalte 0xa2-broken-user-authentication.md 
- [x] Transalte 0xa3-excessive-data-exposure.md 
- [x] Transalte 0xa4-lack-of-resources-and-rate-limiting.md 
- [x] Transalte 0xa5-broken-function-level-authorization.md 
- [x] Transalte 0xa6-mass-assignment.md 
- [x] Transalte 0xa7-security-misconfiguration.md 
- [x] Transalte 0xa8-injection.md 
- [x] Transalte 0xa9-improper-assets-management.md 
- [x] Transalte 0xaa-insufficient-logging-monitoring.md 
- [x] Transalte 0xb0-next-devs.md 
- [x] Transalte 0xb1-next-devsecops.md 
- [x] Transalte 0xd0-about-data.md 
- [x] Transalte 0xd1-acknowledgments.md

**Comment by Malajab** [comment]
All MarkDown Done 👍
