### ISSUE TITLE
ODT Document translation

### ISSUE THREAD

**Issue by KINGSABRI** [Malajab/API-Security#5]
Here are all the document (the odt file) translation tasks

### Tasks list
- [x] Translate header section
- [x] Translate notice section
- [x] Translate toc section
- [x] Translate about-owasp section
- [x] Translate foreword section
- [x] Translate introduction section
- [x] Translate release-notes section
- [x] Translate api-security-risks section
- [x] Translate t10 section
- [x] Translate broken-object-level-authorization section
- [x] Translate broken-user-authentication section
- [x] Translate excessive-data-exposure section
- [x] Translate lack-of-resources-and-rate-limiting section
- [x] Translate broken-function-level-authorization section
- [x] Translate mass-assignment section
- [x] Translate security-misconfiguration section
- [x] Translate injection section
- [x] Translate improper-assets-management section
- [x] Translate insufficient-logging-monitoring section
- [x] Translate next-devs section
- [x] Translate next-devsecops section
- [x] Translate about-data section
- [x] Translate acknowledgments section
