### ISSUE TITLE
Markdown Translation Audit

### ISSUE THREAD

**Issue by KINGSABRI** [Malajab/API-Security#9]
Here are all the Markdown translation Audit tasks

### Tasks list
- [x] Review 0x00-header.md 
- [x] Review 0x00-notice.md 
- [x] Review 0x00-toc.md 
- [x] Review 0x01-about-owasp.md 
- [x] Review 0x02-foreword.md 
- [x] Review 0x03-introduction.md 
- [x] Review 0x04-release-notes.md 
- [x] Review 0x10-api-security-risks.md 
- [x] Review 0x11-t10.md 
- [x] Review 0xa1-broken-object-level-authorization.md 
- [x] Review 0xa2-broken-user-authentication.md 
- [x] Review 0xa3-excessive-data-exposure.md 
- [x] Review 0xa4-lack-of-resources-and-rate-limiting.md 
- [x] Review 0xa5-broken-function-level-authorization.md 
- [x] Review 0xa6-mass-assignment.md 
- [x] Review 0xa7-security-misconfiguration.md 
- [x] Review 0xa8-injection.md (FAD)
- [x] Review 0xa9-improper-assets-management.md (FAD)
- [x] Review 0xaa-insufficient-logging-monitoring.md 
- [x] Review 0xb0-next-devs.md 
- [x] Review 0xb1-next-devsecops.md 
- [x] Review 0xd0-about-data.md 
- [x] Review 0xd1-acknowledgments.md 

Note: The progress here will start after the main task is complete #2

**Comment by fduraibi** [comment]
I am working on "Review 0xa8-injection.md"
